# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TR8Cgu0IILi-4zm5ViefBNLdB2fkr4-8
"""

import pandas as pd
import matplotlib.pyplot as plt
path = "/content/atencion_mujeres_20231005.csv"

df = pd.read_csv(path)
año = df["anio"].value_counts()
plt.barh( año.index, año)
plt.show()